name: aihf
dependencies:
  # ================== 核心Python环境 ==================
  - python=3.11  # 建议升级到3.11以获得更好性能
  - pip

  # ================== Conda优先安装的包 ==================
  - pandas=2.1.4
  - numpy=1.24.4
  - matplotlib=3.9.2
  - tabulate=0.9.0
  - colorama=0.4.6
  - python-dotenv=1.0.0
  - rich=13.9.4

  # ================== 必须通过pip安装的包 ==================
  - pip:
      # LangChain核心生态
      - langchain==0.3.0
      - langchain-anthropic==0.3.5
      - langchain-groq==0.2.3
      - langchain-openai==0.3.5
      - langchain-deepseek==0.1.2
      - langchain-google-genai==2.0.11
      - langgraph==0.2.56
      
      # 交互工具
      - questionary==2.1.0
      
      # 开发工具（原dev依赖）
      - pytest==7.4.0
      - black==23.7.0
      - isort==5.12.0
      - flake8==6.1.0